apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-app-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "node-app-chart.name" . }}
  ports:
    - port: 80
      targetPort: 80
