# permissions for end users to view httpmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: http-operator
    app.kubernetes.io/managed-by: kustomize
  name: httpmonitor-viewer-role
rules:
- apiGroups:
  - monitor.mydomain.com
  resources:
  - httpmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.mydomain.com
  resources:
  - httpmonitors/status
  verbs:
  - get
