# permissions for end users to edit httpmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: http-operator
    app.kubernetes.io/managed-by: kustomize
  name: httpmonitor-editor-role
rules:
- apiGroups:
  - monitor.mydomain.com
  resources:
  - httpmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.mydomain.com
  resources:
  - httpmonitors/status
  verbs:
  - get
