apiVersion: monitor.mydomain.com/v1alpha1
kind: HTTPMonitor
metadata:
  labels:
    app.kubernetes.io/name: http-operator
    app.kubernetes.io/managed-by: kustomize
  name: httpmonitor-sample
spec:
  # TODO(user): Add fields here
