apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: operator
spec:
  selector:
    app: node-app
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      volumes:
      - name: logs
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config

      containers:
      - name: node
        image: node-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /logs
          name: logs

      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/log/nginx
          name: logs
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: nginx-config

      - name: log-tailer
        image: busybox
        command: ["sh", "-c", "tail -n0 -F /var/log/nginx/access.log"]
        volumeMounts:
        - mountPath: /var/log/nginx
          name: logs
