apiVersion: monitor.mydomain.com/v1alpha1
kind: HTTPMonitor
metadata:
  name: http-error-monitor
  namespace: operator
spec: 
  failureThreshold: 5
  windowMinutes: 5
  logFilePath: /var/log/nginx/access.log
  deploymentTarget: node-app
